
meta_product_name: "breakfree"
meta_title: "Signaler une agression ou une situation de harcèlement en quelques minutes."
meta_description: "Signaler une agression, Signaler un harcèlement, Dépôt de plainte, Envoyer un courrier au procureur de la république, Anonyme, Sécurisé, Envoyer un email anonyme, Accompagnement"
meta_image: "https://res.cloudinary.com/dg8fxmpur/image/upload/v1567594044/lighthouse_mtaqbk.png" # should exist in `app/assets/images/`
